
mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_1
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_1/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_1/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_10
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_10/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_10/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_11
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_11/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_11/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_12
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_12/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_12/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_13
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_13/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_13/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_14
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_14/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_14/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_15
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_15/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_15/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_16
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_16/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_16/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_17
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_17/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_17/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_18
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_18/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_18/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_19
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_19/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_19/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_2
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_2/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_2/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_20
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_20/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_20/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_21
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_21/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_21/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_22
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_22/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_22/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_23
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_23/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_23/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_24
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_24/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_24/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_25
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_25/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_25/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_26
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_26/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_26/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_27
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_27/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_27/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_28
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_28/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_28/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_29
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_29/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_29/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_3
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_3/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_3/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_30
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_30/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_30/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_31
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_31/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_31/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_32
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_32/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_32/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_33
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_33/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_33/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_34
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_34/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_34/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_35
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_35/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_35/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_36
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_36/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_36/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_37
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_37/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_37/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_38
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_38/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_38/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_39
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_39/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_39/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_4
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_4/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_4/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_40
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_40/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_40/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_41
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_41/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_41/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_42
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_42/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_42/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_43
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_43/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_43/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_44
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_44/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_44/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_45
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_45/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_45/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_46
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_46/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_46/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_47
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_47/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_47/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_48
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_48/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_48/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_49
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_49/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_49/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_5
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_5/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_5/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_50
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_50/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_50/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_6
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_6/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_6/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_7
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_7/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_7/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_8
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_8/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_8/correspondences.csv

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_9
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_9/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_9/correspondences.csv
