mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_1
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_2
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_3
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_4
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_5
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_6
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/correspondences.csv
mkdir -p data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_7
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/ML_AdaBoost_StandardRecordBlocker/correspondences.csv -O data/correspondences/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/correspondences.csv
