
mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_1

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_10

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_11

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_12

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_13

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_14

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_15

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_16

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_17

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_18

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_19

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_2

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_20

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_21

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_22

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_23

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_24

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_25

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_26

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_27

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_28

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_3

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_4

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_5

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_6

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_7

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_8

mkdir -p data/correspondences/DI3/kaessmannDiseaseAssociations_2_gene2pubtatorcentral_9
