
mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_1/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_1-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_2/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_2-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_3/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_3-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_4/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_4-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_5/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_5-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_6/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_6-ML_SimpleLogistic_StandardRecordBlocker/winter.log

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_AdaBoost_StandardRecordBlocker

mkdir -p data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_SimpleLogistic_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_SimpleLogistic_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_SimpleLogistic_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_SimpleLogistic_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI2/kaessmann_2_all_gene_disease_pmid_associations_7/ML_SimpleLogistic_StandardRecordBlocker/winter.log -O data/input/DI2/kaessmann_2_all_gene_disease_pmid_associations_7-ML_SimpleLogistic_StandardRecordBlocker/winter.log
