
mkdir -p data/input/DI1/Brain_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Brain_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Brain_2_Kidney-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Kidney-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Kidney/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Brain_2_Kidney-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Brain_2_Liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Brain_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Brain_2_Liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Brain_2_Liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Brain_2_Testis-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt

mkdir -p data/input/DI1/Brain_2_Testis-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_Testis/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_Testis-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt

mkdir -p data/input/DI1/Brain_2_mart_export_brain-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Brain_2_mart_export_brain-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Brain_2_mart_export_brain/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Brain_2_mart_export_brain-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Brain-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Brain-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Brain/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Cerebellum_2_Brain-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Kidney-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Kidney/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Cerebellum_2_Kidney-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Cerebellum_2_Liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Testis-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_Testis-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_Testis/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Cerebellum_2_Testis-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Cerebellum_2_mart_export_cerebellum/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Cerebellum_2_mart_export_cerebellum-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Brain-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Brain-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Brain-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Brain-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Brain/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Brain-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Cerebellum-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Cerebellum-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Cerebellum/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Cerebellum-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Kidney-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Kidney-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Kidney-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Kidney/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Kidney-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Testis-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Heart_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Heart_2_Testis-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Heart_2_Testis-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Heart_2_Testis/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Heart_2_Testis-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_Liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Kidney_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_Liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_Liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Kidney_2_Liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_Testis-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Kidney_2_Testis-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_Testis-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_Testis-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_Testis/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Kidney_2_Testis-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Kidney_2_mart_export_kidney/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Kidney_2_mart_export_kidney-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Liver_2_mart_export_liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Liver_2_mart_export_liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Liver_2_mart_export_liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Liver_2_mart_export_liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/Testis_2_Liver-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/Testis_2_Liver-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/Testis_2_Liver-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/Testis_2_Liver-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/Testis_2_Liver/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/Testis_2_Liver-LinearCombination_StandardRecordBlocker/winter.log

mkdir -p data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_SortedNeighbourhoodBlocker/winter.log -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_SortedNeighbourhoodBlocker/winter.log

mkdir -p data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/blockerResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/blockerResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/correspondencesResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/evaluationResultTable.txt -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/evaluationResultTable.txt
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/output/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk/LinearCombination_StandardRecordBlocker/winter.log -O data/input/DI1/mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk-LinearCombination_StandardRecordBlocker/winter.log
