# Get correspondences

// Brain
mkdir -p data/input/correspondences/
mkdir -p data/input/correspondences/Brain_2_mart_export_brain
mkdir -p data/input/correspondences/mart_export_brain_2_all_gene_disease_pmid_associations
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_1
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_2
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_3
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_4
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_5
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_6
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_7
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_8
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_9
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_10
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_11
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_12
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_13
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_14
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_15

// Organs
mkdir -p data/input/correspondences/Heart_2_Brain
Heart_2_Cerebellum
Heart_2_Kidney
Heart_2_Liver
Heart_2_Testis

