
mkdir -p data/input/DI2
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_100_dt.tsv -O data/input/DI2/gene2pubtatorcentral_100_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_100_dt.xml -O data/input/DI2/gene2pubtatorcentral_100_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_101_dt.tsv -O data/input/DI2/gene2pubtatorcentral_101_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_101_dt.xml -O data/input/DI2/gene2pubtatorcentral_101_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_102_dt.tsv -O data/input/DI2/gene2pubtatorcentral_102_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_102_dt.xml -O data/input/DI2/gene2pubtatorcentral_102_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_103_dt.tsv -O data/input/DI2/gene2pubtatorcentral_103_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_103_dt.xml -O data/input/DI2/gene2pubtatorcentral_103_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_104_dt.tsv -O data/input/DI2/gene2pubtatorcentral_104_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_104_dt.xml -O data/input/DI2/gene2pubtatorcentral_104_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_105_dt.tsv -O data/input/DI2/gene2pubtatorcentral_105_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_105_dt.xml -O data/input/DI2/gene2pubtatorcentral_105_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_106_dt.tsv -O data/input/DI2/gene2pubtatorcentral_106_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_106_dt.xml -O data/input/DI2/gene2pubtatorcentral_106_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_107_dt.tsv -O data/input/DI2/gene2pubtatorcentral_107_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_107_dt.xml -O data/input/DI2/gene2pubtatorcentral_107_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_108_dt.tsv -O data/input/DI2/gene2pubtatorcentral_108_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_108_dt.xml -O data/input/DI2/gene2pubtatorcentral_108_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_109_dt.tsv -O data/input/DI2/gene2pubtatorcentral_109_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_109_dt.xml -O data/input/DI2/gene2pubtatorcentral_109_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_10_dt.tsv -O data/input/DI2/gene2pubtatorcentral_10_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_10_dt.xml -O data/input/DI2/gene2pubtatorcentral_10_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_110_dt.tsv -O data/input/DI2/gene2pubtatorcentral_110_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_110_dt.xml -O data/input/DI2/gene2pubtatorcentral_110_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_111_dt.tsv -O data/input/DI2/gene2pubtatorcentral_111_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_111_dt.xml -O data/input/DI2/gene2pubtatorcentral_111_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_112_dt.tsv -O data/input/DI2/gene2pubtatorcentral_112_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_112_dt.xml -O data/input/DI2/gene2pubtatorcentral_112_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_113_dt.tsv -O data/input/DI2/gene2pubtatorcentral_113_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_113_dt.xml -O data/input/DI2/gene2pubtatorcentral_113_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_114_dt.tsv -O data/input/DI2/gene2pubtatorcentral_114_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_114_dt.xml -O data/input/DI2/gene2pubtatorcentral_114_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_115_dt.tsv -O data/input/DI2/gene2pubtatorcentral_115_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_115_dt.xml -O data/input/DI2/gene2pubtatorcentral_115_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_116_dt.tsv -O data/input/DI2/gene2pubtatorcentral_116_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_116_dt.xml -O data/input/DI2/gene2pubtatorcentral_116_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_117_dt.tsv -O data/input/DI2/gene2pubtatorcentral_117_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_117_dt.xml -O data/input/DI2/gene2pubtatorcentral_117_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_118_dt.tsv -O data/input/DI2/gene2pubtatorcentral_118_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_118_dt.xml -O data/input/DI2/gene2pubtatorcentral_118_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_119_dt.tsv -O data/input/DI2/gene2pubtatorcentral_119_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_119_dt.xml -O data/input/DI2/gene2pubtatorcentral_119_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_11_dt.tsv -O data/input/DI2/gene2pubtatorcentral_11_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_11_dt.xml -O data/input/DI2/gene2pubtatorcentral_11_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_120_dt.tsv -O data/input/DI2/gene2pubtatorcentral_120_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_120_dt.xml -O data/input/DI2/gene2pubtatorcentral_120_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_121_dt.tsv -O data/input/DI2/gene2pubtatorcentral_121_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_121_dt.xml -O data/input/DI2/gene2pubtatorcentral_121_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_122_dt.tsv -O data/input/DI2/gene2pubtatorcentral_122_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_122_dt.xml -O data/input/DI2/gene2pubtatorcentral_122_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_123_dt.tsv -O data/input/DI2/gene2pubtatorcentral_123_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_123_dt.xml -O data/input/DI2/gene2pubtatorcentral_123_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_124_dt.tsv -O data/input/DI2/gene2pubtatorcentral_124_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_124_dt.xml -O data/input/DI2/gene2pubtatorcentral_124_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_125_dt.tsv -O data/input/DI2/gene2pubtatorcentral_125_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_125_dt.xml -O data/input/DI2/gene2pubtatorcentral_125_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_126_dt.tsv -O data/input/DI2/gene2pubtatorcentral_126_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_126_dt.xml -O data/input/DI2/gene2pubtatorcentral_126_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_127_dt.tsv -O data/input/DI2/gene2pubtatorcentral_127_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_127_dt.xml -O data/input/DI2/gene2pubtatorcentral_127_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_128_dt.tsv -O data/input/DI2/gene2pubtatorcentral_128_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_128_dt.xml -O data/input/DI2/gene2pubtatorcentral_128_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_129_dt.tsv -O data/input/DI2/gene2pubtatorcentral_129_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_129_dt.xml -O data/input/DI2/gene2pubtatorcentral_129_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_12_dt.tsv -O data/input/DI2/gene2pubtatorcentral_12_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_12_dt.xml -O data/input/DI2/gene2pubtatorcentral_12_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_130_dt.tsv -O data/input/DI2/gene2pubtatorcentral_130_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_130_dt.xml -O data/input/DI2/gene2pubtatorcentral_130_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_131_dt.tsv -O data/input/DI2/gene2pubtatorcentral_131_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_131_dt.xml -O data/input/DI2/gene2pubtatorcentral_131_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_132_dt.tsv -O data/input/DI2/gene2pubtatorcentral_132_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_132_dt.xml -O data/input/DI2/gene2pubtatorcentral_132_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_133_dt.tsv -O data/input/DI2/gene2pubtatorcentral_133_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_133_dt.xml -O data/input/DI2/gene2pubtatorcentral_133_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_134_dt.tsv -O data/input/DI2/gene2pubtatorcentral_134_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_134_dt.xml -O data/input/DI2/gene2pubtatorcentral_134_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_135_dt.tsv -O data/input/DI2/gene2pubtatorcentral_135_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_135_dt.xml -O data/input/DI2/gene2pubtatorcentral_135_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_136_dt.tsv -O data/input/DI2/gene2pubtatorcentral_136_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_136_dt.xml -O data/input/DI2/gene2pubtatorcentral_136_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_137_dt.tsv -O data/input/DI2/gene2pubtatorcentral_137_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_137_dt.xml -O data/input/DI2/gene2pubtatorcentral_137_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_138_dt.tsv -O data/input/DI2/gene2pubtatorcentral_138_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_138_dt.xml -O data/input/DI2/gene2pubtatorcentral_138_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_139_dt.tsv -O data/input/DI2/gene2pubtatorcentral_139_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_139_dt.xml -O data/input/DI2/gene2pubtatorcentral_139_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_13_dt.tsv -O data/input/DI2/gene2pubtatorcentral_13_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_13_dt.xml -O data/input/DI2/gene2pubtatorcentral_13_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_140_dt.tsv -O data/input/DI2/gene2pubtatorcentral_140_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_140_dt.xml -O data/input/DI2/gene2pubtatorcentral_140_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_141_dt.tsv -O data/input/DI2/gene2pubtatorcentral_141_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_141_dt.xml -O data/input/DI2/gene2pubtatorcentral_141_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_142_dt.tsv -O data/input/DI2/gene2pubtatorcentral_142_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_142_dt.xml -O data/input/DI2/gene2pubtatorcentral_142_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_143_dt.tsv -O data/input/DI2/gene2pubtatorcentral_143_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_143_dt.xml -O data/input/DI2/gene2pubtatorcentral_143_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_144_dt.tsv -O data/input/DI2/gene2pubtatorcentral_144_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_144_dt.xml -O data/input/DI2/gene2pubtatorcentral_144_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_145_dt.tsv -O data/input/DI2/gene2pubtatorcentral_145_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_145_dt.xml -O data/input/DI2/gene2pubtatorcentral_145_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_146_dt.tsv -O data/input/DI2/gene2pubtatorcentral_146_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_146_dt.xml -O data/input/DI2/gene2pubtatorcentral_146_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_147_dt.tsv -O data/input/DI2/gene2pubtatorcentral_147_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_147_dt.xml -O data/input/DI2/gene2pubtatorcentral_147_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_148_dt.tsv -O data/input/DI2/gene2pubtatorcentral_148_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_148_dt.xml -O data/input/DI2/gene2pubtatorcentral_148_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_149_dt.tsv -O data/input/DI2/gene2pubtatorcentral_149_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_149_dt.xml -O data/input/DI2/gene2pubtatorcentral_149_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_14_dt.tsv -O data/input/DI2/gene2pubtatorcentral_14_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_14_dt.xml -O data/input/DI2/gene2pubtatorcentral_14_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_150_dt.tsv -O data/input/DI2/gene2pubtatorcentral_150_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_150_dt.xml -O data/input/DI2/gene2pubtatorcentral_150_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_15_dt.tsv -O data/input/DI2/gene2pubtatorcentral_15_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_15_dt.xml -O data/input/DI2/gene2pubtatorcentral_15_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_16_dt.tsv -O data/input/DI2/gene2pubtatorcentral_16_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_16_dt.xml -O data/input/DI2/gene2pubtatorcentral_16_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_17_dt.tsv -O data/input/DI2/gene2pubtatorcentral_17_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_17_dt.xml -O data/input/DI2/gene2pubtatorcentral_17_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_18_dt.tsv -O data/input/DI2/gene2pubtatorcentral_18_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_18_dt.xml -O data/input/DI2/gene2pubtatorcentral_18_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_19_dt.tsv -O data/input/DI2/gene2pubtatorcentral_19_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_19_dt.xml -O data/input/DI2/gene2pubtatorcentral_19_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_1_dt.tsv -O data/input/DI2/gene2pubtatorcentral_1_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_1_dt.xml -O data/input/DI2/gene2pubtatorcentral_1_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_20_dt.tsv -O data/input/DI2/gene2pubtatorcentral_20_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_20_dt.xml -O data/input/DI2/gene2pubtatorcentral_20_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_21_dt.tsv -O data/input/DI2/gene2pubtatorcentral_21_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_21_dt.xml -O data/input/DI2/gene2pubtatorcentral_21_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_22_dt.tsv -O data/input/DI2/gene2pubtatorcentral_22_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_22_dt.xml -O data/input/DI2/gene2pubtatorcentral_22_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_23_dt.tsv -O data/input/DI2/gene2pubtatorcentral_23_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_23_dt.xml -O data/input/DI2/gene2pubtatorcentral_23_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_24_dt.tsv -O data/input/DI2/gene2pubtatorcentral_24_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_24_dt.xml -O data/input/DI2/gene2pubtatorcentral_24_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_25_dt.tsv -O data/input/DI2/gene2pubtatorcentral_25_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_25_dt.xml -O data/input/DI2/gene2pubtatorcentral_25_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_26_dt.tsv -O data/input/DI2/gene2pubtatorcentral_26_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_26_dt.xml -O data/input/DI2/gene2pubtatorcentral_26_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_27_dt.tsv -O data/input/DI2/gene2pubtatorcentral_27_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_27_dt.xml -O data/input/DI2/gene2pubtatorcentral_27_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_28_dt.tsv -O data/input/DI2/gene2pubtatorcentral_28_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_28_dt.xml -O data/input/DI2/gene2pubtatorcentral_28_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_29_dt.tsv -O data/input/DI2/gene2pubtatorcentral_29_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_29_dt.xml -O data/input/DI2/gene2pubtatorcentral_29_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_2_dt.tsv -O data/input/DI2/gene2pubtatorcentral_2_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_2_dt.xml -O data/input/DI2/gene2pubtatorcentral_2_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_30_dt.tsv -O data/input/DI2/gene2pubtatorcentral_30_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_30_dt.xml -O data/input/DI2/gene2pubtatorcentral_30_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_31_dt.tsv -O data/input/DI2/gene2pubtatorcentral_31_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_31_dt.xml -O data/input/DI2/gene2pubtatorcentral_31_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_32_dt.tsv -O data/input/DI2/gene2pubtatorcentral_32_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_32_dt.xml -O data/input/DI2/gene2pubtatorcentral_32_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_33_dt.tsv -O data/input/DI2/gene2pubtatorcentral_33_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_33_dt.xml -O data/input/DI2/gene2pubtatorcentral_33_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_34_dt.tsv -O data/input/DI2/gene2pubtatorcentral_34_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_34_dt.xml -O data/input/DI2/gene2pubtatorcentral_34_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_35_dt.tsv -O data/input/DI2/gene2pubtatorcentral_35_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_35_dt.xml -O data/input/DI2/gene2pubtatorcentral_35_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_36_dt.tsv -O data/input/DI2/gene2pubtatorcentral_36_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_36_dt.xml -O data/input/DI2/gene2pubtatorcentral_36_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_37_dt.tsv -O data/input/DI2/gene2pubtatorcentral_37_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_37_dt.xml -O data/input/DI2/gene2pubtatorcentral_37_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_38_dt.tsv -O data/input/DI2/gene2pubtatorcentral_38_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_38_dt.xml -O data/input/DI2/gene2pubtatorcentral_38_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_39_dt.tsv -O data/input/DI2/gene2pubtatorcentral_39_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_39_dt.xml -O data/input/DI2/gene2pubtatorcentral_39_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_3_dt.tsv -O data/input/DI2/gene2pubtatorcentral_3_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_3_dt.xml -O data/input/DI2/gene2pubtatorcentral_3_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_40_dt.tsv -O data/input/DI2/gene2pubtatorcentral_40_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_40_dt.xml -O data/input/DI2/gene2pubtatorcentral_40_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_41_dt.tsv -O data/input/DI2/gene2pubtatorcentral_41_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_41_dt.xml -O data/input/DI2/gene2pubtatorcentral_41_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_42_dt.tsv -O data/input/DI2/gene2pubtatorcentral_42_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_42_dt.xml -O data/input/DI2/gene2pubtatorcentral_42_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_43_dt.tsv -O data/input/DI2/gene2pubtatorcentral_43_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_43_dt.xml -O data/input/DI2/gene2pubtatorcentral_43_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_44_dt.tsv -O data/input/DI2/gene2pubtatorcentral_44_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_44_dt.xml -O data/input/DI2/gene2pubtatorcentral_44_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_45_dt.tsv -O data/input/DI2/gene2pubtatorcentral_45_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_45_dt.xml -O data/input/DI2/gene2pubtatorcentral_45_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_46_dt.tsv -O data/input/DI2/gene2pubtatorcentral_46_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_46_dt.xml -O data/input/DI2/gene2pubtatorcentral_46_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_47_dt.tsv -O data/input/DI2/gene2pubtatorcentral_47_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_47_dt.xml -O data/input/DI2/gene2pubtatorcentral_47_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_48_dt.tsv -O data/input/DI2/gene2pubtatorcentral_48_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_48_dt.xml -O data/input/DI2/gene2pubtatorcentral_48_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_49_dt.tsv -O data/input/DI2/gene2pubtatorcentral_49_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_49_dt.xml -O data/input/DI2/gene2pubtatorcentral_49_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_4_dt.tsv -O data/input/DI2/gene2pubtatorcentral_4_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_4_dt.xml -O data/input/DI2/gene2pubtatorcentral_4_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_50_dt.tsv -O data/input/DI2/gene2pubtatorcentral_50_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_50_dt.xml -O data/input/DI2/gene2pubtatorcentral_50_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_51_dt.tsv -O data/input/DI2/gene2pubtatorcentral_51_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_51_dt.xml -O data/input/DI2/gene2pubtatorcentral_51_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_52_dt.tsv -O data/input/DI2/gene2pubtatorcentral_52_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_52_dt.xml -O data/input/DI2/gene2pubtatorcentral_52_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_53_dt.tsv -O data/input/DI2/gene2pubtatorcentral_53_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_53_dt.xml -O data/input/DI2/gene2pubtatorcentral_53_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_54_dt.tsv -O data/input/DI2/gene2pubtatorcentral_54_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_54_dt.xml -O data/input/DI2/gene2pubtatorcentral_54_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_55_dt.tsv -O data/input/DI2/gene2pubtatorcentral_55_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_55_dt.xml -O data/input/DI2/gene2pubtatorcentral_55_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_56_dt.tsv -O data/input/DI2/gene2pubtatorcentral_56_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_56_dt.xml -O data/input/DI2/gene2pubtatorcentral_56_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_57_dt.tsv -O data/input/DI2/gene2pubtatorcentral_57_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_57_dt.xml -O data/input/DI2/gene2pubtatorcentral_57_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_58_dt.tsv -O data/input/DI2/gene2pubtatorcentral_58_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_58_dt.xml -O data/input/DI2/gene2pubtatorcentral_58_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_59_dt.tsv -O data/input/DI2/gene2pubtatorcentral_59_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_59_dt.xml -O data/input/DI2/gene2pubtatorcentral_59_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_5_dt.tsv -O data/input/DI2/gene2pubtatorcentral_5_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_5_dt.xml -O data/input/DI2/gene2pubtatorcentral_5_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_60_dt.tsv -O data/input/DI2/gene2pubtatorcentral_60_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_60_dt.xml -O data/input/DI2/gene2pubtatorcentral_60_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_61_dt.tsv -O data/input/DI2/gene2pubtatorcentral_61_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_61_dt.xml -O data/input/DI2/gene2pubtatorcentral_61_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_62_dt.tsv -O data/input/DI2/gene2pubtatorcentral_62_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_62_dt.xml -O data/input/DI2/gene2pubtatorcentral_62_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_63_dt.tsv -O data/input/DI2/gene2pubtatorcentral_63_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_63_dt.xml -O data/input/DI2/gene2pubtatorcentral_63_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_64_dt.tsv -O data/input/DI2/gene2pubtatorcentral_64_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_64_dt.xml -O data/input/DI2/gene2pubtatorcentral_64_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_65_dt.tsv -O data/input/DI2/gene2pubtatorcentral_65_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_65_dt.xml -O data/input/DI2/gene2pubtatorcentral_65_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_66_dt.tsv -O data/input/DI2/gene2pubtatorcentral_66_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_66_dt.xml -O data/input/DI2/gene2pubtatorcentral_66_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_67_dt.tsv -O data/input/DI2/gene2pubtatorcentral_67_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_67_dt.xml -O data/input/DI2/gene2pubtatorcentral_67_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_68_dt.tsv -O data/input/DI2/gene2pubtatorcentral_68_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_68_dt.xml -O data/input/DI2/gene2pubtatorcentral_68_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_69_dt.tsv -O data/input/DI2/gene2pubtatorcentral_69_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_69_dt.xml -O data/input/DI2/gene2pubtatorcentral_69_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_6_dt.tsv -O data/input/DI2/gene2pubtatorcentral_6_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_6_dt.xml -O data/input/DI2/gene2pubtatorcentral_6_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_70_dt.tsv -O data/input/DI2/gene2pubtatorcentral_70_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_70_dt.xml -O data/input/DI2/gene2pubtatorcentral_70_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_71_dt.tsv -O data/input/DI2/gene2pubtatorcentral_71_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_71_dt.xml -O data/input/DI2/gene2pubtatorcentral_71_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_72_dt.tsv -O data/input/DI2/gene2pubtatorcentral_72_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_72_dt.xml -O data/input/DI2/gene2pubtatorcentral_72_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_73_dt.tsv -O data/input/DI2/gene2pubtatorcentral_73_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_73_dt.xml -O data/input/DI2/gene2pubtatorcentral_73_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_74_dt.tsv -O data/input/DI2/gene2pubtatorcentral_74_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_74_dt.xml -O data/input/DI2/gene2pubtatorcentral_74_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_75_dt.tsv -O data/input/DI2/gene2pubtatorcentral_75_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_75_dt.xml -O data/input/DI2/gene2pubtatorcentral_75_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_76_dt.tsv -O data/input/DI2/gene2pubtatorcentral_76_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_76_dt.xml -O data/input/DI2/gene2pubtatorcentral_76_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_77_dt.tsv -O data/input/DI2/gene2pubtatorcentral_77_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_77_dt.xml -O data/input/DI2/gene2pubtatorcentral_77_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_78_dt.tsv -O data/input/DI2/gene2pubtatorcentral_78_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_78_dt.xml -O data/input/DI2/gene2pubtatorcentral_78_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_79_dt.tsv -O data/input/DI2/gene2pubtatorcentral_79_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_79_dt.xml -O data/input/DI2/gene2pubtatorcentral_79_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_7_dt.tsv -O data/input/DI2/gene2pubtatorcentral_7_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_7_dt.xml -O data/input/DI2/gene2pubtatorcentral_7_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_80_dt.tsv -O data/input/DI2/gene2pubtatorcentral_80_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_80_dt.xml -O data/input/DI2/gene2pubtatorcentral_80_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_81_dt.tsv -O data/input/DI2/gene2pubtatorcentral_81_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_81_dt.xml -O data/input/DI2/gene2pubtatorcentral_81_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_82_dt.tsv -O data/input/DI2/gene2pubtatorcentral_82_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_82_dt.xml -O data/input/DI2/gene2pubtatorcentral_82_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_83_dt.tsv -O data/input/DI2/gene2pubtatorcentral_83_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_83_dt.xml -O data/input/DI2/gene2pubtatorcentral_83_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_84_dt.tsv -O data/input/DI2/gene2pubtatorcentral_84_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_84_dt.xml -O data/input/DI2/gene2pubtatorcentral_84_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_85_dt.tsv -O data/input/DI2/gene2pubtatorcentral_85_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_85_dt.xml -O data/input/DI2/gene2pubtatorcentral_85_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_86_dt.tsv -O data/input/DI2/gene2pubtatorcentral_86_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_86_dt.xml -O data/input/DI2/gene2pubtatorcentral_86_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_87_dt.tsv -O data/input/DI2/gene2pubtatorcentral_87_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_87_dt.xml -O data/input/DI2/gene2pubtatorcentral_87_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_88_dt.tsv -O data/input/DI2/gene2pubtatorcentral_88_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_88_dt.xml -O data/input/DI2/gene2pubtatorcentral_88_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_89_dt.tsv -O data/input/DI2/gene2pubtatorcentral_89_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_89_dt.xml -O data/input/DI2/gene2pubtatorcentral_89_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_8_dt.tsv -O data/input/DI2/gene2pubtatorcentral_8_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_8_dt.xml -O data/input/DI2/gene2pubtatorcentral_8_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_90_dt.tsv -O data/input/DI2/gene2pubtatorcentral_90_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_90_dt.xml -O data/input/DI2/gene2pubtatorcentral_90_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_91_dt.tsv -O data/input/DI2/gene2pubtatorcentral_91_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_91_dt.xml -O data/input/DI2/gene2pubtatorcentral_91_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_92_dt.tsv -O data/input/DI2/gene2pubtatorcentral_92_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_92_dt.xml -O data/input/DI2/gene2pubtatorcentral_92_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_93_dt.tsv -O data/input/DI2/gene2pubtatorcentral_93_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_93_dt.xml -O data/input/DI2/gene2pubtatorcentral_93_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_94_dt.tsv -O data/input/DI2/gene2pubtatorcentral_94_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_94_dt.xml -O data/input/DI2/gene2pubtatorcentral_94_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_95_dt.tsv -O data/input/DI2/gene2pubtatorcentral_95_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_95_dt.xml -O data/input/DI2/gene2pubtatorcentral_95_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_96_dt.tsv -O data/input/DI2/gene2pubtatorcentral_96_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_96_dt.xml -O data/input/DI2/gene2pubtatorcentral_96_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_97_dt.tsv -O data/input/DI2/gene2pubtatorcentral_97_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_97_dt.xml -O data/input/DI2/gene2pubtatorcentral_97_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_98_dt.tsv -O data/input/DI2/gene2pubtatorcentral_98_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_98_dt.xml -O data/input/DI2/gene2pubtatorcentral_98_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_99_dt.tsv -O data/input/DI2/gene2pubtatorcentral_99_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_99_dt.xml -O data/input/DI2/gene2pubtatorcentral_99_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_9_dt.tsv -O data/input/DI2/gene2pubtatorcentral_9_dt.tsv
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/gene2pubtatorcentral_9_dt.xml -O data/input/DI2/gene2pubtatorcentral_9_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI2/kaessmann-fused.xml -O data/input/DI2/kaessmann-fused.xml
