## Input datasets
mkdir -p data/input
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/all_gene_disease_pmid_associations_dt.xml -O data/input/all_gene_disease_pmid_associations_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/PubMedDate_dt.xml -O data/input/PubMedDate_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_1_dt.xml -O data/input/gene2pubtatorcentral_1_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_2_dt.xml -O data/input/gene2pubtatorcentral_2_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_3_dt.xml -O data/input/gene2pubtatorcentral_3_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_4_dt.xml -O data/input/gene2pubtatorcentral_4_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_5_dt.xml -O data/input/gene2pubtatorcentral_5_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_6_dt.xml -O data/input/gene2pubtatorcentral_6_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_7_dt.xml -O data/input/gene2pubtatorcentral_7_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_8_dt.xml -O data/input/gene2pubtatorcentral_8_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_9_dt.xml -O data/input/gene2pubtatorcentral_9_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_10_dt.xml -O data/input/gene2pubtatorcentral_10_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_11_dt.xml -O data/input/gene2pubtatorcentral_11_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_12_dt.xml -O data/input/gene2pubtatorcentral_12_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_13_dt.xml -O data/input/gene2pubtatorcentral_13_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_14_dt.xml -O data/input/gene2pubtatorcentral_14_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_15_dt.xml -O data/input/gene2pubtatorcentral_15_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_16_dt.xml -O data/input/gene2pubtatorcentral_16_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_17_dt.xml -O data/input/gene2pubtatorcentral_17_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_18_dt.xml -O data/input/gene2pubtatorcentral_18_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_19_dt.xml -O data/input/gene2pubtatorcentral_19_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_20_dt.xml -O data/input/gene2pubtatorcentral_20_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_21_dt.xml -O data/input/gene2pubtatorcentral_21_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_22_dt.xml -O data/input/gene2pubtatorcentral_22_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_23_dt.xml -O data/input/gene2pubtatorcentral_23_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_24_dt.xml -O data/input/gene2pubtatorcentral_24_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_25_dt.xml -O data/input/gene2pubtatorcentral_25_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_26_dt.xml -O data/input/gene2pubtatorcentral_26_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_27_dt.xml -O data/input/gene2pubtatorcentral_27_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_28_dt.xml -O data/input/gene2pubtatorcentral_28_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_29_dt.xml -O data/input/gene2pubtatorcentral_29_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_30_dt.xml -O data/input/gene2pubtatorcentral_30_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_31_dt.xml -O data/input/gene2pubtatorcentral_31_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_32_dt.xml -O data/input/gene2pubtatorcentral_32_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_33_dt.xml -O data/input/gene2pubtatorcentral_33_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_34_dt.xml -O data/input/gene2pubtatorcentral_34_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_35_dt.xml -O data/input/gene2pubtatorcentral_35_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_36_dt.xml -O data/input/gene2pubtatorcentral_36_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_37_dt.xml -O data/input/gene2pubtatorcentral_37_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_38_dt.xml -O data/input/gene2pubtatorcentral_38_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_39_dt.xml -O data/input/gene2pubtatorcentral_39_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_40_dt.xml -O data/input/gene2pubtatorcentral_40_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_41_dt.xml -O data/input/gene2pubtatorcentral_41_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_42_dt.xml -O data/input/gene2pubtatorcentral_42_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_43_dt.xml -O data/input/gene2pubtatorcentral_43_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_44_dt.xml -O data/input/gene2pubtatorcentral_44_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_45_dt.xml -O data/input/gene2pubtatorcentral_45_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_46_dt.xml -O data/input/gene2pubtatorcentral_46_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_47_dt.xml -O data/input/gene2pubtatorcentral_47_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_48_dt.xml -O data/input/gene2pubtatorcentral_48_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_49_dt.xml -O data/input/gene2pubtatorcentral_49_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_50_dt.xml -O data/input/gene2pubtatorcentral_50_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_51_dt.xml -O data/input/gene2pubtatorcentral_51_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_52_dt.xml -O data/input/gene2pubtatorcentral_52_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_53_dt.xml -O data/input/gene2pubtatorcentral_53_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_54_dt.xml -O data/input/gene2pubtatorcentral_54_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_55_dt.xml -O data/input/gene2pubtatorcentral_55_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_56_dt.xml -O data/input/gene2pubtatorcentral_56_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_57_dt.xml -O data/input/gene2pubtatorcentral_57_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_58_dt.xml -O data/input/gene2pubtatorcentral_58_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_59_dt.xml -O data/input/gene2pubtatorcentral_59_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_60_dt.xml -O data/input/gene2pubtatorcentral_60_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_61_dt.xml -O data/input/gene2pubtatorcentral_61_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_62_dt.xml -O data/input/gene2pubtatorcentral_62_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_63_dt.xml -O data/input/gene2pubtatorcentral_63_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_64_dt.xml -O data/input/gene2pubtatorcentral_64_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_65_dt.xml -O data/input/gene2pubtatorcentral_65_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_66_dt.xml -O data/input/gene2pubtatorcentral_66_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_67_dt.xml -O data/input/gene2pubtatorcentral_67_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_68_dt.xml -O data/input/gene2pubtatorcentral_68_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_69_dt.xml -O data/input/gene2pubtatorcentral_69_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_70_dt.xml -O data/input/gene2pubtatorcentral_70_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_71_dt.xml -O data/input/gene2pubtatorcentral_71_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_72_dt.xml -O data/input/gene2pubtatorcentral_72_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_73_dt.xml -O data/input/gene2pubtatorcentral_73_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_74_dt.xml -O data/input/gene2pubtatorcentral_74_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_75_dt.xml -O data/input/gene2pubtatorcentral_75_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_76_dt.xml -O data/input/gene2pubtatorcentral_76_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_77_dt.xml -O data/input/gene2pubtatorcentral_77_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_78_dt.xml -O data/input/gene2pubtatorcentral_78_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_79_dt.xml -O data/input/gene2pubtatorcentral_79_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_80_dt.xml -O data/input/gene2pubtatorcentral_80_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_81_dt.xml -O data/input/gene2pubtatorcentral_81_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_82_dt.xml -O data/input/gene2pubtatorcentral_82_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_83_dt.xml -O data/input/gene2pubtatorcentral_83_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_84_dt.xml -O data/input/gene2pubtatorcentral_84_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_85_dt.xml -O data/input/gene2pubtatorcentral_85_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_86_dt.xml -O data/input/gene2pubtatorcentral_86_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_87_dt.xml -O data/input/gene2pubtatorcentral_87_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_88_dt.xml -O data/input/gene2pubtatorcentral_88_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_89_dt.xml -O data/input/gene2pubtatorcentral_89_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_90_dt.xml -O data/input/gene2pubtatorcentral_90_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_91_dt.xml -O data/input/gene2pubtatorcentral_91_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_92_dt.xml -O data/input/gene2pubtatorcentral_92_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_93_dt.xml -O data/input/gene2pubtatorcentral_93_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_94_dt.xml -O data/input/gene2pubtatorcentral_94_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_95_dt.xml -O data/input/gene2pubtatorcentral_95_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_96_dt.xml -O data/input/gene2pubtatorcentral_96_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_97_dt.xml -O data/input/gene2pubtatorcentral_97_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_98_dt.xml -O data/input/gene2pubtatorcentral_98_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_99_dt.xml -O data/input/gene2pubtatorcentral_99_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/gene2pubtatorcentral_100_dt.xml -O data/input/gene2pubtatorcentral_100_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Brain_dt.xml -O data/input/Brain_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_brain_dt.xml -O data/input/mart_export_brain_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Cerebellum_dt.xml -O data/input/Cerebellum_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_cerebellum_dt.xml -O data/input/mart_export_cerebellum_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Heart_Ensembl_NCBI_Crosswalk_dt.xml -O data/input/Heart_Ensembl_NCBI_Crosswalk_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Heart_dt.xml -O data/input/Heart_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_heart_dt.xml -O data/input/mart_export_heart_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Kidney_dt.xml -O data/input/Kidney_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_kidney_dt.xml -O data/input/mart_export_kidney_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Liver_dt.xml -O data/input/Liver_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_liver_dt.xml -O data/input/mart_export_liver_dt.xml

wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/Testis_dt.xml -O data/input/Testis_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/mart_export_testis_dt.xml -O data/input/mart_export_testis_dt.xml