mvn compile

# Brain
# genes.IdentityResolution.solutions.Brain.Brain_2_mart_export_brain
mvn exec:java -Dexec.mainClass="genes.IdentityResolution.solutions.Brain.mart_export_brain_2_all_gene_disease_pmid_associations.LR"
# genes.IdentityResolution.solutions.Brain.mart_export_brain_2_all_gene_disease_pmid_associations

# Cerebellum
# genes.IdentityResolution.solutions.Cerebellum.Cerebellum_2_mart_export_cerebellum
# genes.IdentityResolution.solutions.Cerebellum.mart_export_cerebellum_2_all_gene_disease_pmid_associations

# Heart
# genes.IdentityResolution.solutions.Heart.gene_disease_pmid_associations_2_Heart_Ensembl_NCBI_Crosswalk
# genes.IdentityResolution.solutions.Heart.Heart_2_Heart_Ensembl_NCBI_Crosswalk
# genes.IdentityResolution.solutions.Heart.mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk

# Kidney
# genes.IdentityResolution.solutions.Kidney.Kidney_2_mart_export_kidney
# genes.IdentityResolution.solutions.Kidney.mart_export_kidney_2_all_gene_disease_pmid_associations

# Liver
# genes.IdentityResolution.solutions.Liver.Liver_2_mart_export_liver
# genes.IdentityResolution.solutions.Liver.mart_export_liver_2_all_gene_disease_pmid_associations

# Testis
# genes.IdentityResolution.solutions.Testis.mart_export_testis_2_all_gene_disease_pmid_associations
# genes.IdentityResolution.solutions.Testis.Testis_2_mart_export_testis
