# Get correspondences

// Brain
mkdir -p data/input/correspondences/
mkdir -p data/input/correspondences/Brain_2_mart_export_brain
mkdir -p data/input/correspondences/mart_export_brain_2_all_gene_disease_pmid_associations
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_1
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_2
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_3
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_4
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_5
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_6
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_7
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_8
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_9
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_10
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_11
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_12
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_13
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_14
mkdir -p data/input/correspondences/mart_export_brain_2_gene2pubtatorcentral_15

// Cerebellum
Cerebellum_2_mart_export_cerebellum
mart_export_cerebellum_2_all_gene_disease_pmid_associations
mart_export_cerebellum_2_gene2pubtatorcentral_1
mart_export_cerebellum_2_gene2pubtatorcentral_2
mart_export_cerebellum_2_gene2pubtatorcentral_3
mart_export_cerebellum_2_gene2pubtatorcentral_4
mart_export_cerebellum_2_gene2pubtatorcentral_5
mart_export_cerebellum_2_gene2pubtatorcentral_6
mart_export_cerebellum_2_gene2pubtatorcentral_7
mart_export_cerebellum_2_gene2pubtatorcentral_8
mart_export_cerebellum_2_gene2pubtatorcentral_9
mart_export_cerebellum_2_gene2pubtatorcentral_10
mart_export_cerebellum_2_gene2pubtatorcentral_11
mart_export_cerebellum_2_gene2pubtatorcentral_12
mart_export_cerebellum_2_gene2pubtatorcentral_13
mart_export_cerebellum_2_gene2pubtatorcentral_14
mart_export_cerebellum_2_gene2pubtatorcentral_15

// Heart
Heart_2_Heart_Ensembl_NCBI_Crosswalk
Heart_Ensembl_NCBI_Crosswalk_2_all_gene_disease_pmid_associations
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_1
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_2
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_3
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_4
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_5
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_6
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_7
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_8
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_9
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_10
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_11
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_12
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_13
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_14
Heart_Ensembl_NCBI_Crosswalk_2_gene2pubtatorcentral_15
mart_export_heart_2_Heart_Ensembl_NCBI_Crosswalk

// Kidney
Kidney_2_mart_export_kidney
mart_export_kidney_2_all_gene_disease_pmid_associations
mart_export_kidney_2_gene2pubtatorcentral_1
mart_export_kidney_2_gene2pubtatorcentral_2
mart_export_kidney_2_gene2pubtatorcentral_3
mart_export_kidney_2_gene2pubtatorcentral_4
mart_export_kidney_2_gene2pubtatorcentral_5
mart_export_kidney_2_gene2pubtatorcentral_6
mart_export_kidney_2_gene2pubtatorcentral_7
mart_export_kidney_2_gene2pubtatorcentral_8
mart_export_kidney_2_gene2pubtatorcentral_9
mart_export_kidney_2_gene2pubtatorcentral_10
mart_export_kidney_2_gene2pubtatorcentral_11
mart_export_kidney_2_gene2pubtatorcentral_12
mart_export_kidney_2_gene2pubtatorcentral_13
mart_export_kidney_2_gene2pubtatorcentral_14
mart_export_kidney_2_gene2pubtatorcentral_15

// Liver
Liver_2_mart_export_liver
mart_export_liver_2_all_gene_disease_pmid_associations
mart_export_liver_2_gene2pubtatorcentral_1
mart_export_liver_2_gene2pubtatorcentral_2
mart_export_liver_2_gene2pubtatorcentral_3
mart_export_liver_2_gene2pubtatorcentral_4
mart_export_liver_2_gene2pubtatorcentral_5
mart_export_liver_2_gene2pubtatorcentral_6
mart_export_liver_2_gene2pubtatorcentral_7
mart_export_liver_2_gene2pubtatorcentral_8
mart_export_liver_2_gene2pubtatorcentral_9
mart_export_liver_2_gene2pubtatorcentral_10
mart_export_liver_2_gene2pubtatorcentral_11
mart_export_liver_2_gene2pubtatorcentral_12
mart_export_liver_2_gene2pubtatorcentral_13
mart_export_liver_2_gene2pubtatorcentral_14
mart_export_liver_2_gene2pubtatorcentral_15

// Testis
Testis_2_mart_export_testis
mart_export_testis_2_all_gene_disease_pmid_associations
mart_export_testis_2_gene2pubtatorcentral_1
mart_export_testis_2_gene2pubtatorcentral_2
mart_export_testis_2_gene2pubtatorcentral_3
mart_export_testis_2_gene2pubtatorcentral_4
mart_export_testis_2_gene2pubtatorcentral_5
mart_export_testis_2_gene2pubtatorcentral_6
mart_export_testis_2_gene2pubtatorcentral_7
mart_export_testis_2_gene2pubtatorcentral_8
mart_export_testis_2_gene2pubtatorcentral_9
mart_export_testis_2_gene2pubtatorcentral_10
mart_export_testis_2_gene2pubtatorcentral_11
mart_export_testis_2_gene2pubtatorcentral_12
mart_export_testis_2_gene2pubtatorcentral_13
mart_export_testis_2_gene2pubtatorcentral_14
mart_export_testis_2_gene2pubtatorcentral_15

// Organs
Heart_2_Brain
Heart_2_Cerebellum
Heart_2_Kidney
Heart_2_Liver
Heart_2_Testis

// Publication
gene2pubtatorcentral_1_2_PubMedDate
gene2pubtatorcentral_2_2_PubMedDate
gene2pubtatorcentral_3_2_PubMedDate
gene2pubtatorcentral_4_2_PubMedDate
gene2pubtatorcentral_5_2_PubMedDate
gene2pubtatorcentral_6_2_PubMedDate
gene2pubtatorcentral_7_2_PubMedDate
gene2pubtatorcentral_8_2_PubMedDate
gene2pubtatorcentral_9_2_PubMedDate
gene2pubtatorcentral_10_2_PubMedDate
gene2pubtatorcentral_11_2_PubMedDate
gene2pubtatorcentral_12_2_PubMedDate
gene2pubtatorcentral_13_2_PubMedDate
gene2pubtatorcentral_14_2_PubMedDate
gene2pubtatorcentral_15_2_PubMedDate

https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/data-fusion/correspondences/Brain/Brain_2_mart_export_brain/correspondences.csv
