
mkdir -p data/input/DI3
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/DI2_dt.xml -O data/input/DI3/DI2_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/KaessmannDiseaseAssociations_dt.xml -O data/input/DI3/KaessmannDiseaseAssociations_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_10_dt.xml -O data/input/DI3/gene2pubtatorcentral_10_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_11_dt.xml -O data/input/DI3/gene2pubtatorcentral_11_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_12_dt.xml -O data/input/DI3/gene2pubtatorcentral_12_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_13_dt.xml -O data/input/DI3/gene2pubtatorcentral_13_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_14_dt.xml -O data/input/DI3/gene2pubtatorcentral_14_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_15_dt.xml -O data/input/DI3/gene2pubtatorcentral_15_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_16_dt.xml -O data/input/DI3/gene2pubtatorcentral_16_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_17_dt.xml -O data/input/DI3/gene2pubtatorcentral_17_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_18_dt.xml -O data/input/DI3/gene2pubtatorcentral_18_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_19_dt.xml -O data/input/DI3/gene2pubtatorcentral_19_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_1_dt.xml -O data/input/DI3/gene2pubtatorcentral_1_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_20_dt.xml -O data/input/DI3/gene2pubtatorcentral_20_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_21_dt.xml -O data/input/DI3/gene2pubtatorcentral_21_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_22_dt.xml -O data/input/DI3/gene2pubtatorcentral_22_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_23_dt.xml -O data/input/DI3/gene2pubtatorcentral_23_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_24_dt.xml -O data/input/DI3/gene2pubtatorcentral_24_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_25_dt.xml -O data/input/DI3/gene2pubtatorcentral_25_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_26_dt.xml -O data/input/DI3/gene2pubtatorcentral_26_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_27_dt.xml -O data/input/DI3/gene2pubtatorcentral_27_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_28_dt.xml -O data/input/DI3/gene2pubtatorcentral_28_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_29_dt.xml -O data/input/DI3/gene2pubtatorcentral_29_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_2_dt.xml -O data/input/DI3/gene2pubtatorcentral_2_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_30_dt.xml -O data/input/DI3/gene2pubtatorcentral_30_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_31_dt.xml -O data/input/DI3/gene2pubtatorcentral_31_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_32_dt.xml -O data/input/DI3/gene2pubtatorcentral_32_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_33_dt.xml -O data/input/DI3/gene2pubtatorcentral_33_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_34_dt.xml -O data/input/DI3/gene2pubtatorcentral_34_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_35_dt.xml -O data/input/DI3/gene2pubtatorcentral_35_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_36_dt.xml -O data/input/DI3/gene2pubtatorcentral_36_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_37_dt.xml -O data/input/DI3/gene2pubtatorcentral_37_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_38_dt.xml -O data/input/DI3/gene2pubtatorcentral_38_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_39_dt.xml -O data/input/DI3/gene2pubtatorcentral_39_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_3_dt.xml -O data/input/DI3/gene2pubtatorcentral_3_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_40_dt.xml -O data/input/DI3/gene2pubtatorcentral_40_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_41_dt.xml -O data/input/DI3/gene2pubtatorcentral_41_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_42_dt.xml -O data/input/DI3/gene2pubtatorcentral_42_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_43_dt.xml -O data/input/DI3/gene2pubtatorcentral_43_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_44_dt.xml -O data/input/DI3/gene2pubtatorcentral_44_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_45_dt.xml -O data/input/DI3/gene2pubtatorcentral_45_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_46_dt.xml -O data/input/DI3/gene2pubtatorcentral_46_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_47_dt.xml -O data/input/DI3/gene2pubtatorcentral_47_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_48_dt.xml -O data/input/DI3/gene2pubtatorcentral_48_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_49_dt.xml -O data/input/DI3/gene2pubtatorcentral_49_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_4_dt.xml -O data/input/DI3/gene2pubtatorcentral_4_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_50_dt.xml -O data/input/DI3/gene2pubtatorcentral_50_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_5_dt.xml -O data/input/DI3/gene2pubtatorcentral_5_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_6_dt.xml -O data/input/DI3/gene2pubtatorcentral_6_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_7_dt.xml -O data/input/DI3/gene2pubtatorcentral_7_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_8_dt.xml -O data/input/DI3/gene2pubtatorcentral_8_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_9_dt.xml -O data/input/DI3/gene2pubtatorcentral_9_dt.xml
wget https://nahorgebre-ma-650-master-thesis.s3.us-east-2.amazonaws.com/identity-resolution/input/DI3/gene2pubtatorcentral_dt.xml -O data/input/DI3/gene2pubtatorcentral_dt.xml
